[package]
name = "tensor_rotator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
itertools = "0.10.1"
test-case = "1.2.1"
